In [1]:
import numpy as np

In [2]:
a = np.array([3, 1])
b = np.array([1, 3])

c = a + b

print(c)

[4 4]


In [3]:
salarios = np.array([2500, 3200, 4100])

novos_salarios = salarios * 1.08

print(novos_salarios)

[2700. 3456. 4428.]


In [4]:
numeros = np.array([10, 20, 30, 40])

resultado = numeros + 5

print(resultado)

[15 25 35 45]


In [5]:
vendas = np.array([500, 300, 200, 400])
bonus = np.array([50, 30, 20, 40])

print(vendas + bonus)

[550 330 220 440]
